server.port=${PORT:8080}

# Database (use env variables ONLY)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# LocationIQ
locationiq.api.key=${LOCATIONIQ_API_KEY}
locationiq.base.url=https://us1.locationiq.com/v1
